src/commotion.h File Reference
Client API for the Commotion Daemon.
#include <stdbool.h>
*
Typedefs
typedef void co_obj_t
Functions
int co_init (void)
initializes API
int co_shutdown (void)
shuts down the API
co_obj_t * co_connect (const char *uri, const size_t ulen)
creates a connection to Commotion daemon at the given URI
int co_disconnect (co_obj_t *connection)
closes connection to Commotion daemon
co_obj_t * co_request_create (void)
create an API request
int co_request_append (co_obj_t *request, co_obj_t *object)
appends object to request
int co_request_append_str (co_obj_t *request, const char *s, const size_t slen)
appends string to request
int co_request_append_bin (co_obj_t *request, const char *s, const size_t slen)
appends byte array to request
int co_request_append_int (co_obj_t *request, const int i)
appends int to request
int co_request_append_uint (co_obj_t *request, const unsigned int i)
appends unsigned int to request
int co_call (co_obj_t *connection, co_obj_t **response, const char *method, const size_t mlen, co_obj_t *request)
sense procedure call to daemon
co_obj_t * co_response_get (co_obj_t *response, const char *key, const size_t klen)
retrieve object from response
size_t co_response_get_str (co_obj_t *response, char **output, const char *key, const size_t klen)
retrieve string from response
size_t co_response_get_bin (co_obj_t *response, char **output, const char *key, const size_t klen)
retrieve byte array from response
int co_response_get_uint (co_obj_t *response, unsigned long *output, const char *key, const size_t klen)
retrieve unsigned int from response
int co_response_get_int (co_obj_t *response, signed long *output, const char *key, const size_t klen)
retrieve signed int from response
int co_response_get_bool (co_obj_t *response, bool *output, const char *key, const size_t klen)
retrieve bool from response
int co_response_print (co_obj_t *response)
print response object
void co_free (co_obj_t *object)
free API objects
Detailed Description
Client API for the Commotion Daemon.
Author
Josh King (jheretic), jking@chambana.net
Function Documentation
int co_call (co_obj_t * connection, co_obj_t ** response, const char * method, const size_t mlen, co_obj_t * request)
sense procedure call to daemon
Parameters
connection context object for connection
response pointer to response buffer
method method name
mlen length of method name
request request object to send
References co_list_element(), co_list_import(), and co_request_alloc().
{
  CHECK(method != NULL && mlen > 0 && mlen < UINT8_MAX, "Invalid method name.");
  CHECK(connection != NULL && IS_SOCK(connection), "Invalid connection.");
  co_obj_t *params = NULL, *rlist = NULL, *rtree = NULL;
  int retval = 0;
  size_t reqlen = 0;
  ssize_t resplen = 0;
  char req[REQUEST_MAX];
  char resp[RESPONSE_MAX];
  if(request != NULL)
  {
    CHECK(IS_LIST(request), "Not a valid request.");
    params = request;
  }
  else
  {
    params = co_list16_create();
  }
  co_obj_t *m = co_str8_create(method, mlen, 0);
  reqlen = co_request_alloc(req, sizeof(req), m, params);
  CHECK(((co_socket_t*)connection)->send((co_obj_t*)((
      co_socket_t*)connection)->fd, req, reqlen) != -1, "Send error!");
  if((resplen = ((co_socket_t*)connection)->receive(connection, (
      co_obj_t*)((co_socket_t*)connection)->fd, resp, sizeof(resp))) > 0)
  {
    CHECK(co_list_import(&rlist, resp, resplen) > 0, "Failed to parse response.");
    rtree = co_list_element(rlist, 3);
    if(!IS_NIL(rtree))
    {
      retval = 1;
    }
    else
    {
      rtree = co_list_element(rlist, 2);
      retval = 0;
    }
    if(rtree != NULL && IS_TREE(rtree))
    {
      *response = rtree;
      hattach(*response, _pool);
    }
    else SENTINEL("Invalid response.");
  }
  else SENTINEL("Failed to receive data.");
  co_obj_free(m);
  if(params != request) co_obj_free(params);
  return retval;
  
error:
  co_obj_free(m);
  if(params != request) co_obj_free(params);
  return retval;
}
co_obj_t* co_connect (const char * uri, const size_t ulen)
creates a connection to Commotion daemon at the given URI
Parameters
uri URI string
ulen length of URI string
References co_list_append().
{
  CHECK_MEM(_sockets);
  CHECK(uri != NULL && ulen > 0, "Invalid URI.");
  co_obj_t *socket = NEW(co_socket, unix_socket);
  hattach(socket, _pool);
  CHECK((((co_socket_t*)socket)->connect(socket, uri)), "Failed to connect to commotiond at %s\n
      ", uri);
  co_list_append(_sockets, socket);
  return socket;
error:
  co_obj_free(socket);
  return NULL;
}
int co_disconnect (co_obj_t * connection)
closes connection to Commotion daemon
Parameters
connection context object for active connection
References co_list_delete().
{
  CHECK_MEM(connection);
  CHECK_MEM(_sockets);
  CHECK(IS_SOCK(connection), "Specified object is not a Commotion socket.");
  
  co_list_delete(_sockets, connection);
  ((co_socket_t*)connection)->destroy(connection);
  return 1;
error:
  return 0;
}
void co_free (co_obj_t * object)
free API objects
Parameters
object object to free
{
  hattach(object, NULL);
  co_obj_free(object);
  return;
}
int co_request_append (co_obj_t * request, co_obj_t * object)
appends object to request
Parameters
request request object to append to
object object to append
References co_list_append().
{
  CHECK_MEM(request);
  CHECK_MEM(object);
  CHECK(IS_LIST(request), "Not a valid request.");
  return co_list_append(request, object);
error:
  return 0;
}
int co_request_append_bin (co_obj_t * request, const char * s, const size_t slen)
appends byte array to request
Parameters
request request object to append to
s array to append
slen length of array to append
References co_list_append().
{
  CHECK_MEM(request);
  CHECK_MEM(s);
  CHECK(IS_LIST(request), "Not a valid request.");
  CHECK(slen < UINT32_MAX, "Binary is too large.");
  if(slen > UINT16_MAX) return co_list_append(request, co_bin32_create(s, slen, 0));
  if(slen > UINT8_MAX) return co_list_append(request, co_bin16_create(s, slen, 0));
  return co_list_append(request, co_bin8_create(s, slen, 0));
  error:
  return 0;
}
int co_request_append_int (co_obj_t * request, const int i)
appends int to request
Parameters
request request object to append to
i integer to append
References co_list_append().
{
  CHECK_MEM(request);
  CHECK(IS_LIST(request), "Not a valid request.");
  CHECK(i < INT64_MAX && i > INT64_MIN, "Integer out of bounds.");
  if(i > INT32_MAX || i < INT32_MIN) return co_list_append(request, co_int64_create(i, 0));
  if(i > INT16_MAX || i < INT16_MIN) return co_list_append(request, co_int32_create(i, 0));
  if(i > INT8_MAX || i < INT8_MIN) return co_list_append(request, co_int16_create(i, 0));
  return co_list_append(request, co_int8_create(i, 0));
error:
  return 0;
}
int co_request_append_str (co_obj_t * request, const char * s, const size_t slen)
appends string to request
Parameters
request request object to append to
s string to append
slen length of string to append
References co_list_append().
{
  CHECK_MEM(request);
  CHECK_MEM(s);
  CHECK(IS_LIST(request), "Not a valid request.");
  CHECK(slen < UINT32_MAX, "String is too large.");
  if(slen > UINT16_MAX) return co_list_append(request, co_str32_create(s, slen, 0));
  if(slen > UINT8_MAX) return co_list_append(request, co_str16_create(s, slen, 0));
  return co_list_append(request, co_str8_create(s, slen, 0));
error:
  return 0;
}
int co_request_append_uint (co_obj_t * request, const unsigned int i)
appends unsigned int to request
Parameters
request request object to append to
i integer to append
References co_list_append().
{
  CHECK_MEM(request);
  CHECK(IS_LIST(request), "Not a valid request.");
  CHECK(i < UINT64_MAX, "Integer out of bounds.");
  if(i > UINT32_MAX) return co_list_append(request, co_uint64_create(i, 0));
  if(i > UINT16_MAX) return co_list_append(request, co_uint32_create(i, 0));
  if(i > UINT8_MAX) return co_list_append(request, co_uint16_create(i, 0));
  return co_list_append(request, co_uint8_create(i, 0));
error:
  return 0;
}
co_obj_t* co_response_get (co_obj_t * response, const char * key, const size_t klen)
retrieve object from response
Parameters
response pointer to response object
key identifier for response element to retrieve
klen length of key name
References co_tree_find().
Referenced by co_response_get_bin(), co_response_get_bool(), co_response_get_int(), co_response_get_str(), and co_response_get_uint().
{
  CHECK(response != NULL && IS_TREE(response), "Invalid response object.");
  CHECK(key != NULL && klen > 0, "Invalid key.");
  return co_tree_find(response, key, klen);
error:
  return NULL;
}
size_t co_response_get_bin (co_obj_t * response, char ** output, const char * key, const size_t klen)
retrieve byte array from response
Parameters
response pointer to response object
output pointer to output buffer
key identifier for response element to retrieve
klen length of key name
References co_response_get().
{
  co_obj_t *obj = co_response_get(response, key, klen);
  CHECK(obj != NULL, "Response value %s does not exist.", key);
  CHECK(IS_BIN(obj), "Value %s is not a binary.", key);
  return co_obj_data(output, obj);
  error:
  return -1;
}
int co_response_get_bool (co_obj_t * response, bool * output, const char * key, const size_t klen)
retrieve bool from response
Parameters
response pointer to response object
output pointer to output buffer
key identifier for response element to retrieve
klen length of key name
References co_response_get().
                                                                                           {
  co_obj_t *obj = co_response_get(response, key, klen);
  CHECK(obj != NULL, "Response value %s does not exist.", key);
  switch(CO_TYPE(obj))
  {
    case _false:
      *output = false;
      break;
    case _true:
      *output = true;
      break;
    default:
      SENTINEL("Not a boolean.");
      break;
  }
  return 1;
  
  error:
  return 0;
}
int co_response_get_int (co_obj_t * response, signed long * output, const char * key, const size_t klen)
retrieve signed int from response
Parameters
response pointer to response object
output pointer to output buffer
key identifier for response element to retrieve
klen length of key name
References co_response_get().
{
  co_obj_t *obj = co_response_get(response, key, klen);
  CHECK(obj != NULL, "Response value %s does not exist.", key);
  switch(CO_TYPE(obj))
  {
    case _int8:
      *output = (unsigned long)(((co_int8_t *)obj)->data);
      break;
    case _int16:
      *output = (unsigned long)(((co_int16_t *)obj)->data);
      break;
    case _int32:
      *output = (unsigned long)(((co_int32_t *)obj)->data);
      break;
    case _int64:
      *output = (unsigned long)(((co_int64_t *)obj)->data);
      break;
    default:
      SENTINEL("Not an unsigned integer.");
      break;
  }
  return 1;
error:
  return 0;
}
size_t co_response_get_str (co_obj_t * response, char ** output, const char * key, const size_t klen)
retrieve string from response
Parameters
response pointer to response object
output pointer to output buffer
key identifier for response element to retrieve
klen length of key name
References co_response_get().
{
  co_obj_t *obj = co_response_get(response, key, klen);
  CHECK(obj != NULL, "Response value %s does not exist.", key);
  CHECK(IS_STR(obj), "Value %s is not a string.", key);
  return co_obj_data(output, obj);
error:
  return -1;
}
int co_response_get_uint (co_obj_t * response, unsigned long * output, const char * key, const size_t klen)
retrieve unsigned int from response
Parameters
response pointer to response object
output pointer to output buffer
key identifier for response element to retrieve
klen length of key name
References co_response_get().
{
  co_obj_t *obj = co_response_get(response, key, klen);
  CHECK(obj != NULL, "Response value %s does not exist.", key);
  switch(CO_TYPE(obj))
  {
    case _uint8:
      *output = (unsigned long)(((co_uint8_t *)obj)->data);
      break;
    case _uint16:
      *output = (unsigned long)(((co_uint16_t *)obj)->data);
      break;
    case _uint32:
      *output = (unsigned long)(((co_uint32_t *)obj)->data);
      break;
    case _uint64:
      *output = (unsigned long)(((co_uint64_t *)obj)->data);
      break;
    default:
      SENTINEL("Not an unsigned integer.");
      break;
  }
  return 1;
error:
  return 0;
}
int co_response_print (co_obj_t * response)
print response object
Parameters
response pointer to response object
References co_tree_print().
{
  CHECK(response != NULL && IS_TREE(response), "Invalid response object.");
  return co_tree_print(response);
error:
  return 0;
}