plugins/serval-dna/crypto.c File Reference
serval-dna plugin functionality for signing/verifying using Serval keys
#include <stdio.h>
*
#include <string.h>
*
#include <assert.h>
*
#include <serval.h>
*
#include <serval/overlay_address.h>
*
#include <serval/mdp_client.h>
*
#include <serval/crypto.h>
*
#include <serval/str.h>
*
#include `obj.h`
*
#include `list.h`
*
#include `cmd.h`
*
#include `debug.h`
*
#include `crypto.h`
*
#include `tree.h`
*
#include `serval-dna.h`
*
Functions
svl_crypto_ctx * svl_crypto_ctx_new (void)
void svl_crypto_ctx_free (svl_crypto_ctx *ctx)
int serval_open_keyring (svl_crypto_ctx *ctx)
int serval_init_keyring (svl_crypto_ctx *ctx)
int cmd_serval_sign (svl_crypto_ctx *ctx)
int cmd_serval_verify (svl_crypto_ctx *ctx)
int serval_verify_client (svl_crypto_ctx *ctx)
int serval_crypto_register (void)
int olsrd_mdp_register (void)
int olsrd_mdp_sign_register (void)
int serval_crypto_handler (co_obj_t *self, co_obj_t **output, co_obj_t *params)
int olsrd_mdp_init (co_obj_t *self, co_obj_t **output, co_obj_t *params)
int olsrd_mdp_sign (co_obj_t *self, co_obj_t **output, co_obj_t *params)
Variables
keyring_file * keyring
struct subscriber * my_subscriber
char * serval_path = NULL
co_obj_t * err_msg = NULL
Detailed Description
serval-dna plugin functionality for signing/verifying using Serval keys
Author
Dan Staples (dismantl), danstaples@opentechinstitute.org
Function Documentation
int olsrd_mdp_register (void)
name: mdp-init param[0] <required>: <keyring_path> (co_str16_t) param[1] <required>: <SID> (co_str8_t)
References name.
{
  /**
   * name: mdp-init
   * param[0] <required>: <keyring_path> (co_str16_t)
   * param[1] <required>: <SID> (co_str8_t)
   */
  const char name[] = "mdp-init";
  
  CHECK(co_cmd_register(name, sizeof(name), "", 1, "", 1, olsrd_mdp_init), "Failed to register command");
  
  return 1;
error:
  return 0;
}
int olsrd_mdp_sign (co_obj_t * self, co_obj_t ** output, co_obj_t * params)
skipping some error checking for performance reasons
References co_list_element().
Referenced by olsrd_mdp_sign_register().
{
  int ret = 0;
  svl_crypto_ctx *ctx = svl_crypto_ctx_new();
  
  /** skipping some error checking for performance reasons */
  
// CHECK(IS_LIST(params) && co_list_length(params) == 2, "Invalid params");
  
  ctx->msg_len = co_obj_data((char**)&ctx->msg, co_list_element(params, 1));
  
  memcpy(ctx->sas_private,_LIST_ELEMENT(params, 0),crypto_sign_SECRETKEYBYTES);
  
  CHECK(serval_create_signature(ctx), "Failed to sign OLSRd packet");
  
  CMD_OUTPUT("sig", co_bin8_create((char*)ctx->signature, SIGNATURE_BYTES, 0));
  
  ret = 1;
error:
  svl_crypto_ctx_free(ctx);
  return ret;
}
int olsrd_mdp_sign_register (void)
name: mdp-sign param[0] <required>: key (co_bin8_t) param[1] <required>: data (co_bin?_t)
References name, and olsrd_mdp_sign().
{
  /**
   * name: mdp-sign
   * param[0] <required>: key (co_bin8_t)
   * param[1] <required>: data (co_bin?_t)
   */
  
  const char name[] = "mdp-sign";
  
  CHECK(co_cmd_register(name, sizeof(name), "", 1, "", 1, olsrd_mdp_sign), "Failed to
       register command");
  
  return 1;
error:
  return 0;
}
int serval_crypto_register (void)
name: serval-crypto param[0] - param[3]: (co_str?_t)
References desc, name, and usage.
{
  /** name: serval-crypto
   * param[0] - param[3]: (co_str?_t)
   */
  
  const char name[] = "serval-crypto",
  usage[] = "serval-crypto sign [<SID>] <MESSAGE> [--keyring=<KEYRING_PATH>]\n"
            "serval-crypto verify <SAS> <SIGNATURE> <MESSAGE>",
  desc[] = "Serval-crypto utilizes Serval's crypto API to:\n"
      " * Sign any arbitrary text using a Serval key. If no Serval key ID (SID) is given,\n"
      " a new key will be created on the default Serval keyring.\n"
      " * Verify any arbitrary text, a signature, and a Serval signing key (SAS), and will\n"
      " determine if the signature is valid.";
  
  int reg_ret = co_cmd_register(name,
        sizeof(name),
        usage,
        sizeof(usage),
        desc,
        sizeof(desc),
        serval_crypto_handler);
  CHECK(reg_ret, "Failed to register commands");
  
  return 1;
error:
  return 0;
}