src/iface.h File Reference
interface handling for the Commotion daemon
#include <stdbool.h>
*
#include <net/if.h>
*
#include `id.h`
*
#include `obj.h`
*
Classes
struct co_iface_t
contains the file descriptor, interface status (up or down), profile name, interface frequency struct, wpa control struct, wpa id, and a bool to indicare whether the interface is wireless or not
Macros
#define FREQ_LEN 5
#define MAC_LEN 6
#define WPA_REPLY_SIZE 2048
#define IFACES_MAX 32
#define SIOCGIWNAME 0x8B01
Typedefs
typedef struct co_iface_t co_iface_t
Enumerations
enum co_iface_status_t { DOWN = 0,
UP = 1
 }
Functions
struct co_iface_t __attribute__ ((packed))
int co_ifaces_create (void)
checks for available interfaces
void co_ifaces_shutdown (void)
removes all interfaces
int co_iface_remove (char *iface_name)
removes an interface from the list of available interfaces
co_obj_t * co_iface_add (const char *iface_name, const int family)
adds a new interface to the list of available interfaces, and checks whether it is IPv4 and IPv6 capable, and whether it is wireless
int co_iface_wpa_connect (co_obj_t *iface)
connects the commotion interface to wpa supplicant
int co_iface_wpa_disconnect (co_obj_t *iface)
turns off wpa supplicant
int co_iface_get_mac (co_obj_t *iface, unsigned char *output, int output_size)
int co_iface_set_ip (co_obj_t *iface, const char *ip_addr, const char *netmask)
sets ip address and netmask for commotion interface
int co_iface_unset_ip (co_obj_t *iface)
Resets ip address of chosen interface.
int co_iface_set_ssid (co_obj_t *iface, const char *ssid)
sets SSID from profile or uses default
int co_iface_set_bssid (co_obj_t *iface, const char *bssid)
sets BSSID from profile or uses default
int co_iface_set_frequency (co_obj_t *iface, const int frequency)
sets wireless frequency (eg. channel) from profile or uses default
int co_iface_set_encryption (co_obj_t *iface, const char *proto)
specifies the wpa encryption protocol
int co_iface_set_key (co_obj_t *iface, const char *key)
specifies the wpa encryption key
int co_iface_set_mode (co_obj_t *iface, const char *mode)
specifies the Wi-Fi mode
int co_iface_set_apscan (co_obj_t *iface, const int value)
sets AP_SCAN value
int co_iface_wireless_enable (co_obj_t *iface)
enables specified wireless network
int co_iface_wireless_disable (co_obj_t *iface)
disables specified wireless network
int co_set_dns (const char *dnsserver, const char *searchdomain, const char *resolvpath)
sets DNS name server and sets search domain
int co_generate_ip (const char *base, const char *genmask, const nodeid_t id, char *output, int type)
generates an ip table for a commotion interface
char * co_iface_profile (char *iface_name)
sets node configuration profile
co_obj_t * co_iface_get (char *iface_name)
retrieves node configuration profile
Variables
co_obj_t _header
uint8_t _exttype
uint8_t _len
int fd
co_iface_status_t status
char * profile
struct ifreq ifr
struct wpa_ctrl * ctrl
int wpa_id
bool wireless
Detailed Description
interface handling for the Commotion daemon
Author
Josh King (jheretic), jking@chambana.net
Enumeration Type Documentation
enum co_iface_status_t
indicates whether the interface is UP(1) or DOWN(0)
             {
  DOWN = 0,
  UP = 1
} co_iface_status_t;
Function Documentation
int co_generate_ip (const char * base, const char * genmask, const nodeid_t id, char * output, int type)
generates an ip table for a commotion interface
Parameters
base base address
genmask genmask
id the node id
type whether the device is a gateway (1) or not (0)
                                                                                                     {
  nodeid_t addr;
  addr.id = 0;
  struct in_addr baseaddr;
  struct in_addr generatedaddr;
  struct in_addr genmaskaddr;
  CHECK(inet_aton(base, &baseaddr) != 0, "Invalid base ip address %s", base);
  CHECK(inet_aton(genmask, &genmaskaddr) != 0, "Invalid genmask address %s", genmask);
  /*
   * Turn the IP address into a
   * network address.
   */
  generatedaddr.s_addr = (baseaddr.s_addr & genmaskaddr.s_addr);
  /*
   * get the matching octet from
   * the mac and and then move it
   * left to the proper spot.
   */
  for (int i = 0; i < 4; i++)
    addr.bytes[i] = (id.bytes[i]&0xff)%0xfe;
  /*
   * if address is of a gateway
   * type, then set the last byte
   * to '1'
   * */
  if(type) {
    /*
     * shift us over by one
     * to ensure that we are
     * getting maximum entropy
     * from the mac address.
     */
    addr.bytes[1] = addr.bytes[2];
    addr.bytes[2] = addr.bytes[3];
    addr.bytes[3] = 1;
  }
  /*
   * mask out the parts of address
   * that overlap with the genmask
   */
  addr.id &= ~(genmaskaddr.s_addr);
  /*
   * add back the user-supplied
   * base ip address.
   */
  generatedaddr.s_addr = (generatedaddr.s_addr|addr.id);
  strcpy(output, inet_ntoa(generatedaddr));
  return 1;
error:
  return 0;
}
co_obj_t* co_iface_add (const char * iface_name, const int family)
adds a new interface to the list of available interfaces, and checks whether it is IPv4 and IPv6 capable, and whether it is wireless
Parameters
iface_name name of the interface
family address family of the interface. Must be AF_INET (IPv4) or AF_INET6 (IPv6), which uses host and port number for addressing
References co_list_append(), and strlcpy().
                                                                 {
  co_iface_t *iface = h_calloc(1,sizeof(co_iface_t));
  iface->_len = (sizeof(co_iface_t));
  iface->_exttype = _iface;
  iface->_header._type = _ext8;
  iface->_header._flags = 0;
  iface->_header._ref = 0;
  
  iface->fd = socket(PF_INET, SOCK_DGRAM, IPPROTO_IP);
  strlcpy(iface->ifr.ifr_name, iface_name, IFNAMSIZ);
  
 /* Check whether interface is IPv4 or IPv6 */
  if((family & AF_INET) == AF_INET) {
    iface->ifr.ifr_addr.sa_family = AF_INET;
  } else if((family & AF_INET6) == AF_INET6) {
    iface->ifr.ifr_addr.sa_family = AF_INET6;
  } else {
    ERROR("Invalid address family!");
    co_obj_free((co_obj_t*)iface);
    return NULL;
  }
  /* Check whether interface is wireless or not */
  if(_co_iface_is_wireless((co_obj_t*)iface)) iface->wireless = true;
  iface->wpa_id = -1;
    
  co_list_append(ifaces, (co_obj_t*)iface);
  return (co_obj_t*)iface;
}
co_obj_t* co_iface_get (char * iface_name)
retrieves node configuration profile
Parameters
iface_name name of interface
References co_list_parse().
                                         {
  co_obj_t *iface = NULL;
  CHECK((iface = co_list_parse(ifaces, _co_iface_match_i, iface_name)) != NULL, "Failed to get
       interface %s!", iface_name);
  return iface;
error:
  return NULL;
}
int co_iface_get_mac (co_obj_t * iface, unsigned char * output, int output_size)
Parameters
iface interface object
output output of hardware MAC address lookup
output_size size of MAC address. Must be six bytes
                                                                              {
  CHECK(IS_IFACE(iface),"Not an iface.");
  co_iface_t *maciface = NULL;
  CHECK(output_size == 6, "output_size does not equal six");
  maciface = malloc(sizeof(co_iface_t));
  memset(maciface, '\0', sizeof(co_iface_t));
  memmove(maciface, iface, sizeof(co_iface_t));
  if (0 == ioctl(((co_iface_t*)iface)->fd, SIOCGIFHWADDR, &maciface->ifr)) {
    DEBUG("Received MAC Address : %02x:%02x:%02x:%02x:%02x:%02x\n",
                maciface->ifr.ifr_hwaddr.sa_data[0],maciface->ifr.ifr_hwaddr.sa_data[1],maciface->ifr.
      ifr_hwaddr.sa_data[2]
                ,maciface->ifr.ifr_hwaddr.sa_data[3],maciface->ifr.ifr_hwaddr.sa_data[4],maciface->ifr.
      ifr_hwaddr.sa_data[5]);
    memmove(output, maciface->ifr.ifr_addr.sa_data, output_size);
    free(maciface);
    return 1;
  }
  free(maciface);
error:
  return 0;
}
char* co_iface_profile (char * iface_name)
sets node configuration profile
Parameters
iface_name name of interface
References co_list_parse().
                                         {
  co_obj_t *iface = NULL;
  CHECK((iface = co_list_parse(ifaces, _co_iface_match_i, iface_name)) != NULL, "Failed to get
       interface %s profile!", iface_name);
  return ((co_iface_t*)iface)->profile;
error:
  return NULL;
}
int co_iface_remove (char * iface_name)
removes an interface from the list of available interfaces
Parameters
iface_name name of interface to be removed
References co_iface_unset_ip(), co_iface_wireless_disable(), co_iface_wpa_disconnect(), co_list_delete(), and co_list_parse().
                                      {
  co_obj_t *iface = NULL;
  CHECK((iface = co_list_parse(ifaces, _co_iface_match_i, iface_name)) != NULL, "Failed to
       delete interface %s!", iface_name);
  iface = co_list_delete(ifaces, iface);
  co_iface_unset_ip(iface);
  co_iface_wireless_disable(iface);
  co_iface_wpa_disconnect(iface);
  co_obj_free(iface);
  return 1;
error:
  return 0;
}
int co_iface_set_apscan (co_obj_t * iface, const int value)
sets AP_SCAN value
Parameters
iface interface object
value desired value for AP_SCAN
                                                          {
  CHECK(IS_IFACE(iface),"Not an iface.");
  char cmd[256];
  char buf[WPA_REPLY_SIZE];
  size_t len;
  snprintf(cmd, sizeof(cmd), "AP_SCAN %d", value);
  cmd[sizeof(cmd) - 1] = '\0';
  return _co_iface_wpa_command(iface, cmd, buf, &len);
error:
  return 0;
}
int co_iface_set_bssid (co_obj_t * iface, const char * bssid)
sets BSSID from profile or uses default
Parameters
iface interface object
bssid desired BSSID
                                                           {
  CHECK(IS_IFACE(iface),"Not an iface.");
  char cmd[256], *pos, *end;
  int ret;
  char buf[WPA_REPLY_SIZE];
  size_t len;
  end = cmd + sizeof(cmd);
  pos = cmd;
  ret = snprintf(pos, end - pos, "BSSID");
  if (ret < 0 || ret >= end - pos) {
    ERROR("Too long BSSID command.");
    return 0;
  }
  pos += ret;
  ret = snprintf(pos, end - pos, " %d %s", ((co_iface_t*)iface)->wpa_id, bssid);
  if (ret < 0 || ret >= end - pos) {
    ERROR("Too long BSSID command.");
    return 0;
  }
  pos += ret;
  return _co_iface_wpa_command(iface, cmd, buf, &len);
error:
  return 0;
}
int co_iface_set_encryption (co_obj_t * iface, const char * proto)
specifies the wpa encryption protocol
Parameters
iface interface object
proto desired protocol
                                                                {
  CHECK(IS_IFACE(iface),"Not an iface.");
  return _co_iface_wpa_set(iface, "proto", proto);
error:
  return 0;
}
int co_iface_set_frequency (co_obj_t * iface, const int frequency)
sets wireless frequency (eg. channel) from profile or uses default
Parameters
iface interface object
frequency desired frequency
                                                                 {
  CHECK(IS_IFACE(iface),"Not an iface.");
  char freq[FREQ_LEN];
  snprintf(freq, FREQ_LEN, "%d", frequency);
  return _co_iface_wpa_set(iface, "frequency", freq);
error:
  return 0;
}
int co_iface_set_ip (co_obj_t * iface, const char * ip_addr, const char * netmask)
sets ip address and netmask for commotion interface
Parameters
iface interface object
ip_addr ip address for the socket
netmask netmask for the socket
                                                                                   {
  CHECK_MEM(iface_obj);
  co_iface_t *iface = (co_iface_t*)iface_obj;
  struct sockaddr_in *addr = (struct sockaddr_in *)&iface->ifr.ifr_addr;
  DEBUG("Setting address %s and netmask %s.", ip_addr, netmask);
 
  // Convert IP from numbers and dots to binary notation
  inet_pton(AF_INET, ip_addr, &addr->sin_addr);
  CHECK((ioctl(iface->fd, SIOCSIFADDR, &iface->ifr) == 0), "Failed to set IP address for interface: %s",
      iface->ifr.ifr_name);
  inet_pton(AF_INET, netmask, &addr->sin_addr);
  CHECK((ioctl(iface->fd, SIOCSIFNETMASK, &iface->ifr) == 0), "Failed to set IP address for interface: %s",
       iface->ifr.ifr_name);
  //Get and set interface flags.
  CHECK((ioctl(iface->fd, SIOCGIFFLAGS, &iface->ifr) == 0), "Interface shutdown: %s", iface->ifr.ifr_name);
  iface->ifr.ifr_flags |= IFF_UP;
  iface->ifr.ifr_flags |= IFF_RUNNING;
  CHECK((ioctl(iface->fd, SIOCSIFFLAGS, &iface->ifr) == 0), "Interface up failed: %s", iface->ifr.ifr_name)
      ;
 
  DEBUG("Addressing for interface %s is done!", iface->ifr.ifr_name);
  return 1;
error:
  return 0;
}
int co_iface_set_key (co_obj_t * iface, const char * key)
specifies the wpa encryption key
Parameters
iface interface object
key desired key
                                                       {
  CHECK(IS_IFACE(iface),"Not an iface.");
  return _co_iface_wpa_set(iface, "psk", key);
error:
  return 0;
}
int co_iface_set_mode (co_obj_t * iface, const char * mode)
specifies the Wi-Fi mode
Parameters
iface interface object
mode desired mode
                                                         {
  CHECK(IS_IFACE(iface),"Not an iface.");
  return _co_iface_wpa_set(iface, "mode", mode);
error:
  return 0;
}
int co_iface_set_ssid (co_obj_t * iface, const char * ssid)
sets SSID from profile or uses default
Parameters
iface interface object
ssid desired SSID
                                                         {
  CHECK(IS_IFACE(iface),"Not an iface.");
  return _co_iface_wpa_set(iface, "ssid", ssid);
error:
  return 0;
}
int co_iface_unset_ip (co_obj_t * iface)
Resets ip address of chosen interface.
Parameters
iface interface object
Referenced by co_iface_remove().
                                           {
  CHECK_MEM(iface_obj);
  CHECK(IS_IFACE(iface_obj),"Not an iface.");
  co_iface_t *iface = (co_iface_t*)iface_obj;
  //Get and set interface flags.
  CHECK((ioctl(iface->fd, SIOCGIFFLAGS, &iface->ifr) == 0), "Interface shutdown: %s", iface->ifr.ifr_name);
  iface->ifr.ifr_flags &= ~IFF_UP;
  iface->ifr.ifr_flags &= ~IFF_RUNNING;
  CHECK((ioctl(iface->fd, SIOCSIFFLAGS, &iface->ifr) == 0), "Interface up failed: %s", iface->ifr.ifr_name)
      ;
  return 1;
error:
  return 0;
}
int co_iface_wireless_disable (co_obj_t * iface)
disables specified wireless network
Parameters
iface interface object
Referenced by co_iface_remove().
                                               {
  CHECK(IS_IFACE(iface),"Not an iface.");
  CHECK(_co_iface_wpa_disable_network(iface), "Failed to disable network %s", ((
      co_iface_t*)iface)->ifr.ifr_name);
  CHECK(_co_iface_wpa_remove_network(iface), "Failed to remove network %s", ((
      co_iface_t*)iface)->ifr.ifr_name);
  return 1;
error:
  return 0;
}
int co_iface_wireless_enable (co_obj_t * iface)
enables specified wireless network
Parameters
iface interface object
                                              {
  CHECK(IS_IFACE(iface),"Not an iface.");
  char cmd[256];
  char buf[WPA_REPLY_SIZE];
  size_t len;
  snprintf(cmd, sizeof(cmd), "ENABLE_NETWORK %d", ((co_iface_t*)iface)->wpa_id);
  cmd[sizeof(cmd) - 1] = '\0';
  return _co_iface_wpa_command(iface, cmd, buf, &len);
error:
  return 0;
}
int co_iface_wpa_connect (co_obj_t * iface)
connects the commotion interface to wpa supplicant
Parameters
iface interface object
                                              {
  CHECK(IS_IFACE(iface_obj),"Not an iface.");
  co_iface_t *iface = (co_iface_t*)iface_obj;
  char *filename = NULL;
  size_t length;
  CHECK(iface->wireless, "Not a wireless interface: %s", iface->ifr.ifr_name);
  length = strlen(wpa_control_dir) + strlen(iface->ifr.ifr_name) + 2;
  filename = calloc(1, length);
  CHECK_MEM(filename);
  snprintf(filename, length, "%s/%s", wpa_control_dir, iface->ifr.ifr_name);
  DEBUG("WPA control file: %s", filename);
  CHECK((iface->ctrl = wpa_ctrl_open(filename)), "Failed to connect to wpa_supplicant.");
  free(filename);
  return 1;
error:
  free(filename);
  return 0;
}
int co_iface_wpa_disconnect (co_obj_t * iface)
turns off wpa supplicant
Parameters
iface interface object
Referenced by co_iface_remove().
                                                 {
  CHECK(IS_IFACE(iface_obj),"Not an iface.");
  co_iface_t *iface = (co_iface_t*)iface_obj;
  if(iface->ctrl) {
    wpa_ctrl_detach(iface->ctrl);
    wpa_ctrl_close(iface->ctrl);
    return 1;
  }
error:
  return 0;
}
int co_set_dns (const char * dnsserver, const char * searchdomain, const char * resolvpath)
sets DNS name server and sets search domain
Parameters
dnsserver IP addresss of DNS server
searchdomain desired search domain
resolvpath filepath to resolv.conf
                                                                                        {
  FILE *fp = fopen(resolvpath, "w+");
  if(fp != NULL) {
    if(searchdomain != NULL) fprintf(fp, "search %s\n", searchdomain);
    fprintf(fp, "nameserver %s\n", dnsserver);
    fclose(fp);
    return 1;
  } else ERROR("Could not open file: %s", resolvpath);
  return 0;
}