src/tree.h File Reference
String-indexed search tree for Commotion object system.
#include <stdlib.h>
*
#include <stddef.h>
*
#include <stdint.h>
*
#include `debug.h`
*
#include `extern/halloc.h`
*
Classes
struct _treenode_t
Macros
#define _DECLARE_TREE(L)
Typedefs
typedef struct _treenode_t _treenode_t
Functions
struct _treenode_t __attribute__ ((packed))
_DECLARE_TREE (16)
_DECLARE_TREE (32)
co_obj_t * co_node_key (_treenode_t *node)
return key object for given node
co_obj_t * co_node_value (_treenode_t *node)
return value object for given node
_treenode_t * co_tree_find_node (_treenode_t *root, const char *key, const size_t klen)
find node in given tree
_treenode_t * co_tree_root (const co_obj_t *tree)
return root node of tree object
ssize_t co_tree_length (co_obj_t *tree)
return length (number of key-value pairs) of given tree
co_obj_t * co_tree_find (const co_obj_t *root, const char *key, const size_t klen)
return value from given tree that corresponds to key
co_obj_t * co_tree_delete (co_obj_t *root, const char *key, const size_t klen)
delete value from given tree that corresponds to key
int co_tree_insert (co_obj_t *root, const char *key, const size_t klen, co_obj_t *value)
insert object into given tree and associate with key
int co_tree_insert_unsafe (co_obj_t *root, const char *key, const size_t klen, co_obj_t *value)
insert object into given tree and associate with key, where value is not tied to tree
int co_tree_insert_force (co_obj_t *root, const char *key, const size_t klen, co_obj_t *value)
insert object into given tree and associate with key (overwrite if it exists)
int co_tree_insert_unsafe_force (co_obj_t *root, const char *key, const size_t klen, co_obj_t *value)
insert object into given tree and associate with key, where value is not tied to tree (overwrite if it exists)
int co_tree_set_str (co_obj_t *root, const char *key, const size_t klen, const char *value, const size_t vlen)
set value contained in an object in the tree with a specified key (if a string)
int co_tree_set_int (co_obj_t *root, const char *key, const size_t klen, const signed long value)
set value contained in an object in the tree with a specified key (if an int)
int co_tree_set_uint (co_obj_t *root, const char *key, const size_t klen, const unsigned long value)
set value contained in an object in the tree with a specified key (if an unsigned int)
int co_tree_set_float (co_obj_t *root, const char *key, const size_t klen, const double value)
set value contained in an object in the tree with a specified key (if a float)
int co_tree_process (co_obj_t *tree, const co_iter_t iter, void *context)
process tree with given iterator function
void co_tree_destroy (co_obj_t *root)
free tree structure
size_t co_tree_raw (char *output, const size_t olen, const co_obj_t *tree)
dump raw representation of tree
size_t co_tree_import (co_obj_t **tree, const char *input, const size_t ilen)
import raw representation of tree
void co_tree_print_indent (co_obj_t *tree, int indent)
print tree with indent
int co_tree_print (co_obj_t *tree)
print tree
int co_tree_print_raw (co_obj_t *tree)
print raw dump of tree
Variables
char splitchar
_treenode_t * low
_treenode_t * equal
_treenode_t * high
co_obj_t * key
co_obj_t * value
Detailed Description
String-indexed search tree for Commotion object system.
Author
Josh King (jheretic), jking@chambana.net
Macro Definition Documentation
#define _DECLARE_TREE(L)
Value:
typedef struct __attribute__((packed)) { co_obj_t _header; uint##L##_t _len; \
  _treenode_t *root;} co_tree##L##_t; int co_tree##L##_alloc(\
  co_obj_t *output); co_obj_t *co_tree##L##_create(void);
Function Documentation
co_obj_t* co_node_key (_treenode_t * node)
return key object for given node
Parameters
node node to return object for
{
  if(node != NULL)
    return node->key;
  else
    return NULL;
}
co_obj_t* co_node_value (_treenode_t * node)
return value object for given node
Parameters
node node to return object for
{
  if(node != NULL)
    return node->value;
  else
    return NULL;
}
co_obj_t* co_tree_delete (co_obj_t * root, const char * key, const size_t klen)
delete value from given tree that corresponds to key
Parameters
root tree object
key key to search for
klen length of key
{
  co_obj_t *value = NULL;
  if(CO_TYPE(root) == _tree16)
  {
    ((co_tree16_t *)root)->root = _co_tree_delete_r(((co_tree16_t *)root)->root, \
      ((co_tree16_t *)root)->root, key, klen, &value);
  }
  else if(CO_TYPE(root) == _tree32)
  {
    ((co_tree32_t *)root)->root = _co_tree_delete_r(((co_tree32_t *)root)->root, \
      ((co_tree32_t *)root)->root, key, klen, &value);
  }
  CHECK(value != NULL, "Failed to delete value.");
  CHECK(_co_tree_decrement(root) >= 0, "Failed to decrement value.");
  return value;
error:
  return NULL;
}
void co_tree_destroy (co_obj_t * root)
free tree structure
Parameters
root tree object to free
{
    if(root) {
        h_free(root);
    }
}
co_obj_t* co_tree_find (const co_obj_t * root, const char * key, const size_t klen)
return value from given tree that corresponds to key
Parameters
root tree object
key key to search for
klen length of key
References co_tree_find_node(), and co_tree_root().
Referenced by co_cmd_desc(), co_cmd_exec(), co_cmd_hook(), co_cmd_hook_str(), co_cmd_usage(), co_profile_get(), co_profile_get_float(), co_profile_get_int(), co_profile_get_str(), co_profile_get_uint(), and co_response_get().
{
  DEBUG("Get from tree: %s", key);
  _treenode_t *n = NULL;
  CHECK((n = co_tree_root(root)) != NULL, "Specified object is not a tree.");
  n = co_tree_find_node(n, key, klen);
  CHECK(n != NULL, "Unable to find value.");
  return n->value;
error:
  return NULL;
}
_treenode_t* co_tree_find_node (_treenode_t * root, const char * key, const size_t klen)
find node in given tree
Parameters
root tree in which to search
key key to search for
klen length of key
Referenced by co_tree_find(), co_tree_insert(), co_tree_insert_unsafe(), co_tree_set_float(), co_tree_set_int(), co_tree_set_str(), and co_tree_set_uint().
{
  _treenode_t *n = root;
  size_t i = 0;
  while(i < klen && n)
  {
    if (key[i] < n->splitchar)
    {
      n = n->low;
    }
    else if (key[i] == n->splitchar)
    {
      i++;
      if(i < klen) n = n->equal;
    }
    else
    {
      n = n->high;
    }
  }
  if(n)
  {
    return n;
  }
  else
  {
    return NULL;
  }
}
size_t co_tree_import (co_obj_t ** tree, const char * input, const size_t ilen)
import raw representation of tree
Parameters
tree target pointer of new, imported tree object
input input buffer
ilen length of input buffer
References co_list_import(), co_tree_import(), and co_tree_insert().
Referenced by co_list_import(), and co_tree_import().
{
  size_t length = 0, olen = 0, read = 0, klen = 0;
  char *kstr = NULL;
  int i = 0;
  co_obj_t *obj = NULL;
  const char *cursor = input;
  switch((uint8_t)input[0])
  {
    case _tree16:
      length = *((uint16_t *)(input + 1));
      *tree = co_tree16_create();
      cursor += sizeof(uint16_t) + 1;
      read = sizeof(uint16_t) + 1;
      break;
    case _tree32:
      length = (uint32_t)(*(uint32_t*)(input + 1));
      *tree = co_tree32_create();
      cursor += sizeof(uint32_t) + 1;
      read = sizeof(uint32_t) + 1;
      break;
    default:
      SENTINEL("Not a tree.");
      break;
  }
  while(i < length && read <= ilen)
  {
    DEBUG("Importing tuple:");
    if((uint8_t)cursor[0] == _str8)
    {
      DEBUG("Reading key...");
      cursor += 1;
      read += 1;
      klen = (uint8_t)cursor[0];
      kstr = (char *)&cursor[1];
      cursor += klen + 1;
      read += klen + 1;
      DEBUG("Reading value...");
      switch((uint8_t)cursor[0])
      {
        case _list16:
        case _list32:
          olen = co_list_import(&obj, cursor, ilen - read);
          break;
        case _tree16:
        case _tree32:
          olen = co_tree_import(&obj, cursor, ilen - read);
          break;
        default:
          olen = co_obj_import(&obj, cursor, ilen - read, 0);
          break;
      }
      CHECK(olen > 0, "Failed to import object.");
      cursor +=olen;
      read += olen;
      DEBUG("Inserting value into tree with key.");
      CHECK(co_tree_insert(*tree, kstr, klen, obj), "Failed to insert object.");
      i++;
    }
  }
  return read;
error:
  if(obj != NULL) co_obj_free(obj);
  return -1;
}
int co_tree_insert (co_obj_t * root, const char * key, const size_t klen, co_obj_t * value)
insert object into given tree and associate with key
Parameters
root tree object
key key to search for
klen length of key
value value object to insert
References co_tree_find_node(), and co_tree_root().
Referenced by co_tree_import(), and dispatcher_cb().
{
  _treenode_t *n = co_tree_find_node(co_tree_root(root), key, klen)
      ;
  CHECK(n == NULL, "Key exists.");
  return _co_tree_insert(root, key, klen, value, true);
error:
  return 0;
}
int co_tree_insert_force (co_obj_t * root, const char * key, const size_t klen, co_obj_t * value)
insert object into given tree and associate with key (overwrite if it exists)
Parameters
root tree object
key key to search for
klen length of key
value value object to insert
{
  return _co_tree_insert(root, key, klen, value, true);
}
int co_tree_insert_unsafe (co_obj_t * root, const char * key, const size_t klen, co_obj_t * value)
insert object into given tree and associate with key, where value is not tied to tree
Parameters
root tree object
key key to search for
klen length of key
value value object to insert
References co_tree_find_node(), and co_tree_root().
{
  _treenode_t *n = co_tree_find_node(co_tree_root(root), key, klen)
      ;
  CHECK(n == NULL, "Key exists.");
  return _co_tree_insert(root, key, klen, value, false);
error:
  return 0;
}
int co_tree_insert_unsafe_force (co_obj_t * root, const char * key, const size_t klen, co_obj_t * value)
insert object into given tree and associate with key, where value is not tied to tree (overwrite if it exists)
Parameters
root tree object
key key to search for
klen length of key
value value object to insert
{
  return _co_tree_insert(root, key, klen, value, false);
}
ssize_t co_tree_length (co_obj_t * tree)
return length (number of key-value pairs) of given tree
Parameters
tree tree object
{
  return _co_tree_change_length(tree, 0);
}
int co_tree_print (co_obj_t * tree)
print tree
Parameters
tree tree object to print
References co_tree_print_indent().
Referenced by co_response_print().
{
  CHECK_MEM(tree);
  co_tree_print_indent(tree,0);
  return 1;
error:
  return 0;
}
void co_tree_print_indent (co_obj_t * tree, int indent)
print tree with indent
Parameters
tree tree object to print
indent level of indent
References co_tree_root().
Referenced by co_tree_print().
{
  int count = 0;
  
  for (int i = 0; i < indent; i++) printf(" ");
  printf("{\n");
  _co_tree_print_r(tree, co_tree_root(tree), &count, indent+1);
  for (int i = 0; i < indent; i++) printf(" ");
  printf("}");
  if (!indent) printf("\n");
}
int co_tree_print_raw (co_obj_t * tree)
print raw dump of tree
Parameters
tree tree object to print
References co_tree_root().
{
  CHECK_MEM(tree);
  _co_tree_print_raw_r(tree, co_tree_root(tree));
  return 1;
error:
  return 0;
}
int co_tree_process (co_obj_t * tree, const co_iter_t iter, void * context)
process tree with given iterator function
Parameters
tree tree object to process
iter iterator function
context additional arguments to iterator
Referenced by co_cmd_process().
{
  switch(CO_TYPE(tree))
  {
    case _tree16:
      _co_tree_process_r(tree, ((co_tree16_t *)tree)->root, iter, context);
      break;
    case _tree32:
      _co_tree_process_r(tree, ((co_tree32_t *)tree)->root, iter, context);
      break;
    default:
      SENTINEL("Object is not a tree.");
      break;
  }
  return 1;
error:
  return 0;
}
size_t co_tree_raw (char * output, const size_t olen, const co_obj_t * tree)
dump raw representation of tree
Parameters
output output buffer
olen length of output buffer
tree tree to dump
References co_tree_root().
Referenced by co_list_raw(), and co_response_alloc().
{
  char *out = output;
  size_t written = 0;
  switch(CO_TYPE(tree))
  {
    case _tree16:
      memmove(out, &(tree->_type), sizeof(tree->_type));
      out += sizeof(tree->_type);
      written += sizeof(tree->_type);
      memmove(out, &(((co_tree16_t *)tree)->_len), sizeof(((co_tree16_t *)tree)->_len));
      out += sizeof(((co_tree16_t *)tree)->_len);
      written += sizeof(((co_tree16_t *)tree)->_len);
      break;
    case _tree32:
      memmove(out, &(tree->_type), sizeof(tree->_type));
      out += sizeof(tree->_type);
      written += sizeof(tree->_type);
      memmove(out, &(((co_tree32_t *)tree)->_len), sizeof(((co_tree32_t *)tree)->_len));
      out += sizeof(((co_tree32_t *)tree)->_len);
      written += sizeof(((co_tree32_t *)tree)->_len);
      break;
    default:
      SENTINEL("Not a tree object.");
      break;
  }
  
  _co_tree_raw_r(&out, &olen, &written, co_tree_root(tree));
  DEBUG("Tree bytes written: %d", (int)written);
  return written;
error:
  return -1;
}
_treenode_t* co_tree_root (const co_obj_t * tree)
return root node of tree object
Parameters
tree tree object that contains root
Referenced by co_profile_export_file(), co_tree_find(), co_tree_insert(), co_tree_insert_unsafe(), co_tree_print_indent(), co_tree_print_raw(), co_tree_raw(), co_tree_set_float(), co_tree_set_int(), co_tree_set_str(), and co_tree_set_uint().
{
  CHECK_MEM(tree);
  _treenode_t *n = NULL;
  if(CO_TYPE(tree) == _tree16)
  {
    n = ((co_tree16_t *)tree)->root;
  }
  else if(CO_TYPE(tree) == _tree32)
  {
    n = ((co_tree32_t *)tree)->root;
  }
  else SENTINEL("Specified object is not a tree.");
  return n;
error:
  return NULL;
}
int co_tree_set_float (co_obj_t * root, const char * key, const size_t klen, const double value)
set value contained in an object in the tree with a specified key (if a float)
Parameters
root tree object
key key to search for
klen length of key
value value to insert
References co_tree_find_node(), and co_tree_root().
Referenced by co_profile_set_float().
{
  DEBUG("Get from tree: %s", key);
  _treenode_t *n = NULL;
  CHECK((n = co_tree_root(root)) != NULL, "Specified object is not a tree.");
  n = co_tree_find_node(n, key, klen);
  CHECK(n != NULL, "Failed to find key in tree.");
  CHECK(_co_node_set_float(n, value), "Unable to set float for node.");
  return 1;
error:
  return 0;
}
int co_tree_set_int (co_obj_t * root, const char * key, const size_t klen, const signed long value)
set value contained in an object in the tree with a specified key (if an int)
Parameters
root tree object
key key to search for
klen length of key
value value to insert
References co_tree_find_node(), and co_tree_root().
Referenced by co_profile_set_int().
{
  DEBUG("Get from tree: %s", key);
  _treenode_t *n = NULL;
  CHECK((n = co_tree_root(root)) != NULL, "Specified object is not a tree.");
  n = co_tree_find_node(n, key, klen);
  CHECK(n != NULL, "Failed to find key in tree.");
  CHECK(_co_node_set_int(n, value), "Unable to set integer for node.");
  return 1;
error:
  return 0;
}
int co_tree_set_str (co_obj_t * root, const char * key, const size_t klen, const char * value, const size_t vlen)
set value contained in an object in the tree with a specified key (if a string)
Parameters
root tree object
key key to search for
klen length of key
value value to insert
vlen length of value
References co_tree_find_node(), and co_tree_root().
Referenced by co_profile_set_str().
{
  DEBUG("Get from tree: %s", key);
  _treenode_t *n = NULL;
  CHECK((n = co_tree_root(root)) != NULL, "Specified object is not a tree.");
  n = co_tree_find_node(n, key, klen);
  CHECK(n != NULL, "Failed to find key in tree.");
  CHECK(_co_node_set_str(n, value, vlen), "Unable to set string for node.");
  return 1;
error:
  return 0;
}
int co_tree_set_uint (co_obj_t * root, const char * key, const size_t klen, const unsigned long value)
set value contained in an object in the tree with a specified key (if an unsigned int)
Parameters
root tree object
key key to search for
klen length of key
value value to insert
References co_tree_find_node(), and co_tree_root().
Referenced by co_profile_set_uint().
{
  DEBUG("Get from tree: %s", key);
  _treenode_t *n = NULL;
  CHECK((n = co_tree_root(root)) != NULL, "Specified object is not a tree.");
  n = co_tree_find_node(n, key, klen);
  CHECK(n != NULL, "Failed to find key in tree.");
  CHECK(_co_node_set_uint(n, value), "Unable to set unsigned integer for node.");
  return 1;
error:
  return 0;
}