src/util.c File Reference
utility functions for the Commotion daemon
#include <stdlib.h>
*
#include <dirent.h>
*
#include <unistd.h>
*
#include <fcntl.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <arpa/inet.h>
*
#include <ctype.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <stdint.h>
*
#include `debug.h`
*
#include `util.h`
*
#include `extern/md5.h`
*
Macros
#define HEXDUMP_COLS 8
Functions
size_t strlcpy (char *dest, const char *src, const size_t size)
copies a string
size_t strlcat (char *dst, const char *src, const size_t size)
concatenates two strings
size_t snprintfcat (char *str, size_t size, const char *format,...)
prints output from string `str` in a specified format
size_t strstrip (const char *s, char *out, size_t outlen)
removes white space from a given string (to parse for arguments)
int compare_version (const char *aver, const char *bver)
compares version numbers of two software releases
int process_files (const char *dir_path, file_iter loader)
processes file paths
int string_to_argv (const char *input, char **argv, int *argc, const size_t max)
parses a string and converts into a set of arguments
int argv_to_string (char **argv, const int argc, char *output, const size_t max)
converts argument vectors to a single string
void mac_string_to_bytes (char *macstr, unsigned char mac[6])
converts a MAC address from a string to individual bytes
void print_mac (unsigned char mac[6])
prints MAC address from MAC array
int wifi_freq (const int channel)
sets Wi-Fi frequency corresponding to specified channel
int wifi_chan (const int frequency)
sets Wi-Fi channel corresponding to specified freuency
void get_bssid (const char *essid, const unsigned int chan, char *bssid)
generates a BSSID from hash of ESSID and channel
void hexdump (void *mem, unsigned int len)
prints a raw byte array in hex and ascii output
Detailed Description
utility functions for the Commotion daemon
Author
Josh King (jheretic), jking@chambana.net
Macro Definition Documentation
#define HEXDUMP_COLS 8
from http://grapsus.net/blog/post/Hexadecimal-dump-in-C
Referenced by hexdump().
Function Documentation
int argv_to_string (char ** argv, const int argc, char * output, const size_t max)
converts argument vectors to a single string
Parameters
argv pointer to argument list
argc number of arguments
output concatenated string of arguments
max maximum length of the string
References strlcat().
                                                                                {
  int i;
  for(i = 0; i < argc; i++) {
    strlcat(output, argv[i], max);
    strlcat(output, " ", max);
  }
  if(i < argc) {
    ERROR("Failed to concatenate all of argv.");
    return 0;
  }
  return 1;
}
int compare_version (const char * aver, const char * bver)
compares version numbers of two software releases
Parameters
aver version number for software 'a'
bver version number for software 'b'
                                                        {
  char *a, *b, *anext, *bnext;
  long int avalue, bvalue;
  // Grab pointer to first number in each version string.
  a = strpbrk(aver, "0123456789");
  b = strpbrk(bver, "0123456789");
  while(a && b) {
    // Convert characters to number.
    avalue = strtol(a, &anext, 10);
    bvalue = strtol(b, &bnext, 10);
    if(avalue < bvalue) return -1;
    if(avalue > bvalue) return 1;
    a = strpbrk(anext, "0123456789");
    b = strpbrk(bnext, "0123456789");
  }
  // If valid characters remain in 1 string, assume a point release.
  if(b) return -1;
  if(a) return 1;
  // Versions are identical.
  return 0;
}
void get_bssid (const char * essid, const unsigned int channel, char * bssid)
generates a BSSID from hash of ESSID and channel
Parameters
essid The ESSID to hash
channel an integer of the channel
bbsid The returned 6-byte BSSID
                                                                        {
  DEBUG("ESSID: %s, Channel: %d", essid, chan);
  unsigned char hash[BSSID_SIZE];
  memset(hash, '\0', sizeof(hash));
  char channel[CHAN_SIZE];
  memset(channel, '\0', sizeof(channel));
  int i;
  MD5_CTX ctx;
  MD5_Init(&ctx);
  MD5_Update(&ctx, essid, strlen(essid));
  MD5_Final(hash, &ctx);
  DEBUG("Hash: %s", (char *)hash);
  for(i = 0; i < BSSID_SIZE - CHAN_SIZE; i++)
  {
    bssid[i] = hash[i];
    DEBUG("BSSID byte %d as char: %c, as int: %d", i, bssid[i], bssid[i]);
  }
  /*
   * Set the first byte to 0x02 (the value of
   * a link-local ethernet address) which is
   * required for a valid bssid.
   */
  bssid[0] = 0x02;
  bssid[i] = chan / 10;
  bssid[i + 1] = chan % 10;
  DEBUG("BSSID buffer: %s", (char *)bssid);
  return;
}
void hexdump (void * mem, unsigned int len)
prints a raw byte array in hex and ascii output
Parameters
mem the byte array to print
len length of the byte array
References HEXDUMP_COLS.
{
  unsigned int i, j;
  
  for(i = 0; i < len + ((len % HEXDUMP_COLS) ? (HEXDUMP_COLS - len %
      HEXDUMP_COLS) : 0); i++)
  {
    /* print offset */
    if(i % HEXDUMP_COLS == 0)
    {
      printf("0x%06x: ", i);
    }
    
    /* print hex data */
    if(i < len)
    {
      printf("%02x ", 0xFF & ((char*)mem)[i]);
    }
    else /* end of block, just aligning for ASCII dump */
    {
      printf(" ");
    }
    
    /* print ASCII dump */
    if(i % HEXDUMP_COLS == (HEXDUMP_COLS - 1))
    {
      for(j = i - (HEXDUMP_COLS - 1); j <= i; j++)
      {
  if(j >= len) /* end of block, not really printing */
  {
    putchar(' ');
  }
  else if(isprint(((char*)mem)[j])) /* printable char */
  {
    putchar(0xFF & ((char*)mem)[j]);
  }
  else /* other char */
  {
    putchar('.');
  }
      }
      putchar('\n');
    }
  }
}
void mac_string_to_bytes (char * macstr, unsigned char mac[6])
converts a MAC address from a string to individual bytes
Parameters
macstr MAC string
mac an array for storing the MAC address
                                                             {
  memset(mac, '\0', 6);
  sscanf(macstr, "%hhx:%hhx:%hhx:%hhx:%hhx:%hhx", &mac[0], &mac[1], &mac[2], &mac[3], &mac[4], &mac[5]);
  return;
}
void print_mac (unsigned char mac[6])
prints MAC address from MAC array
Parameters
mac array storing MAC address
                                     {
  printf("%02x:%02x:%02x:%02x:%02x:%02x", mac[0] & 0xff, mac[1] & 0xff, mac[2] & 0xff, mac[3] & 0xff, mac[4
      ] & 0xff, mac[5] & 0xff);
  return;
}
int process_files (const char * dir_path, file_iter loader)
processes file paths
Parameters
dir_path string of the directory path
loader number of directories in the file path
Referenced by co_plugins_load(), and co_profile_import_files().
                                                          {
  size_t path_size = strlen(dir_path);
  CHECK((path_size > 0) && (path_size <= PATH_MAX), "Invalid path length!");
  DIR *dir_iter = NULL;
  CHECK((dir_iter = opendir(dir_path)), "Could not read directory!");
  struct dirent *dir_entry = NULL;
  DEBUG("Processing files in directory %s", dir_path);
  
  while((dir_entry = readdir(dir_iter)) != NULL) {
    DEBUG("Checking file %s", dir_entry->d_name);
    if(!strcmp(dir_entry->d_name, ".")) continue;
    if(!strcmp(dir_entry->d_name, "..")) continue;
    if(!(*loader)(dir_path, dir_entry->d_name)) break;
  }
  if(dir_iter) closedir(dir_iter);
  return 1;
error:
  return 0;
}
size_t snprintfcat (char * str, size_t size, const char * format, ...)
prints output from string `str` in a specified format
Parameters
str string to be printed
size size of string
format output format
                                                                    {
  size_t result;
  va_list args;
  size_t len = strnlen(str, size);
  va_start(args, format);
  result = vsnprintf(str + len, size - len, format, args);
  va_end(args);
  return result + len;
}
int string_to_argv (const char * input, char ** argv, int * argc, const size_t max)
parses a string and converts into a set of arguments
Parameters
input the string to be parsed
argv pointer to argument list
argc number of arguments read from the string
max maximum length of string
                                                                                {
  int count = 0;
  char *saveptr = NULL;
  char *token = NULL;
  char *input_tmp = strdup(input);
  CHECK_MEM(token = strtok_r(input_tmp, " ", &saveptr));
  while(token && count < max) {
    argv[count++] = token;
    token = strtok_r(NULL, " ", &saveptr);
  }
  *argc = count;
  return 1;
error:
  free(input_tmp);
  return 0;
}
size_t strlcat (char * dst, const char * src, const size_t size)
concatenates two strings
Parameters
dst destination for new string
src string to be added to
size size of combined strings
Referenced by argv_to_string().
{
  size_t used, length, copy;
  used = strlen(dst);
  length = strlen(src);
  if (size > 0 && used < size - 1) {
    copy = (length >= size - used) ? size - used - 1 : length;
    memcpy(dst + used, src, copy);
    dst[used + copy] = '\0';
  }
  return used + length;
}
size_t strlcpy (char * dest, const char * src, const size_t size)
copies a string
Parameters
dst destination for new string
src string to be copied
size size of string
Referenced by co_iface_add(), and strstrip().
{
  const size_t length = strlen(src);
  if (size != 0) {
    memmove(dest, src, (length > size - 1) ? size - 1 : length);
    dest[size - 1] = '\0';
  }
  return length;
}
size_t strstrip (const char * s, char * out, const size_t outlen)
removes white space from a given string (to parse for arguments)
Parameters
s string to parse
out output from the string (with white space removed)
outlen length of the output
References strlcpy().
                                                         {
  size_t len = strlen(s);
  const char *ptr = s;
  if(len == 0) return 0;
  while(*ptr && isspace(*ptr)) {
    ++ptr;
    --len;
  }
  if(len <= outlen) {
    strlcpy(out, ptr, len + 1);
    return len;
  } else return -1;
}
int wifi_chan (const int frequency)
sets Wi-Fi channel corresponding to specified freuency
Parameters
frequency specified frequency
                                   {
  if(frequency < 5080) {
    return (frequency - 5000)/5;
  }
  switch(frequency) {
    case 2412:
      return 1;
      break;
    case 2417:
      return 2;
      break;
    case 2422:
      return 3;
      break;
    case 2427:
      return 4;
      break;
    case 2432:
      return 5;
      break;
    case 2437:
      return 6;
      break;
    case 2442:
      return 7;
      break;
    case 2447:
      return 8;
      break;
    case 2452:
      return 9;
      break;
    case 2457:
      return 10;
      break;
    case 2462:
      return 11;
      break;
    case 2467:
      return 12;
      break;
    case 2472:
      return 13;
      break;
    case 2484:
      return 14;
      break;
    default:
      ERROR("Not a valid frequency!");
      return 0;
  }
}
int wifi_freq (const int channel)
sets Wi-Fi frequency corresponding to specified channel
Parameters
channel specified channel
                                 {
  if(channel > 14) {
    return 5000 + 5*channel;
  }
  switch(channel) {
    case 1:
      return 2412;
      break;
    case 2:
      return 2417;
      break;
    case 3:
      return 2422;
      break;
    case 4:
      return 2427;
      break;
    case 5:
      return 2432;
      break;
    case 6:
      return 2437;
      break;
    case 7:
      return 2442;
      break;
    case 8:
      return 2447;
      break;
    case 9:
      return 2452;
      break;
    case 10:
      return 2457;
      break;
    case 11:
      return 2462;
      break;
    case 12:
      return 2467;
      break;
    case 13:
      return 2472;
      break;
    case 14:
      return 2484;
      break;
    default:
      ERROR("Not a valid channel!");
      return 0;
  }
}