src/plugin.h File Reference
The commotiond plugin loader.
#include <stdlib.h>
*
#include `obj.h`
*
Classes
struct co_plugin_t
Typedefs
typedef struct co_plugin_t co_plugin_t
Functions
struct co_plugin_t __attribute__ ((packed))
int co_plugins_shutdown (void)
shuts down and closes all plugins
int co_plugins_start (void)
starts all loaded plugins
int co_plugins_init (size_t index_size)
initializes global plugin list
int co_plugins_load (const char *dir_path)
loads all plugins in specified path
Variables
co_obj_t _header
uint8_t _exttype
uint8_t _len
co_obj_t * name
co_obj_t * filename
co_cb_t shutdown
co_cb_t init
void * handle
Detailed Description
The commotiond plugin loader.
Author
Josh King (jheretic), jking@chambana.net
Function Documentation
int co_plugins_init (size_t index_size)
initializes global plugin list
Parameters
index_size specifies size of index for plugins list (16 or 32 bit)
References co_plugins_shutdown().
Referenced by main().
{
  if(index_size == 16)
  {
    CHECK((_plugins = (co_obj_t *)co_list16_create()) != NULL, "Plugin list creation failed.");
  }
  else if(index_size == 32)
  {
    CHECK((_plugins = (co_obj_t *)co_list32_create()) != NULL, "Plugin list creation failed.");
  }
  else SENTINEL("Invalid list index size.");
  return 1;
error:
  co_plugins_shutdown();
  return 0;
}
int co_plugins_load (const char * dir_path)
loads all plugins in specified path
Parameters
dir_path directory to load plugins from
References process_files().
Referenced by main().
                                          {
  return process_files(dir_path, _co_plugins_load_i);
}
Variable Documentation
co_obj_t* name
command name