src/profile.h File Reference
a key-value store for loading configuration information
#include <stdlib.h>
*
#include <stddef.h>
*
#include `obj.h`
*
Classes
struct co_cbptr_t
struct co_profile_t
Macros
#define SCHEMA(N) static int schema_##N(co_obj_t *self, co_obj_t **output, co_obj_t *params)
#define SCHEMA_ADD(K, V)
#define SCHEMA_REGISTER(N) co_schema_register(schema_##N)
#define SCHEMA_GLOBAL(N) co_schema_register_global(schema_##N)
Typedefs
typedef struct co_cbptr_t co_cbptr_t
typedef struct co_profile_t co_profile_t
Functions
struct co_cbptr_t __attribute__ ((packed))
int co_schema_register (co_cb_t cb)
register a callback for populating a profile schema
int co_schema_register_global (co_cb_t cb)
register a callback for populating global profile
int co_schemas_load (co_obj_t *profile)
load schemas for specified profile
int co_profiles_create (const size_t index_size)
create global profiles list
int co_profiles_init (const size_t index_size)
creates a list of available profiles
void co_profiles_shutdown (void)
removes the list of available profiles
int co_profile_import_files (const char *path)
imports available profiles from profiles directory
int co_profile_import_global (const char *path)
imports global profile
co_obj_t * co_profile_find (co_obj_t *name)
searches the profile list for a specified profile
co_obj_t * co_profile_global (void)
returns the global profile
void co_profile_delete_global (void)
deletes the global profile
int co_profile_add (const char *name, const size_t nlen)
adds a new profile
int co_profile_remove (const char *name, const size_t nlen)
removes profile with given name
void co_profile_dump (co_obj_t *profile)
dumps profile data
co_obj_t * co_profile_get (co_obj_t *profile, const co_obj_t *key)
returns the key value (if an int) from the profile. If no value set, returns the default value
int co_profile_set_str (co_obj_t *profile, const char *key, const size_t klen, const char *value, const size_t vlen)
sets a specified profile value (if a string)
size_t co_profile_get_str (co_obj_t *profile, char **output, const char *key, const size_t klen)
returns the key value (if a string) from the profile. If no value set, returns the default value
int co_profile_set_int (co_obj_t *profile, const char *key, const size_t klen, const signed long value)
sets a specified profile value (if an int)
signed long co_profile_get_int (co_obj_t *profile, const char *key, const size_t klen)
returns the key value (if an int) from the profile. If no value set, returns the default value
int co_profile_set_uint (co_obj_t *profile, const char *key, const size_t klen, const unsigned long value)
sets a specified profile value (if an unsigned int)
unsigned long co_profile_get_uint (co_obj_t *profile, const char *key, const size_t klen)
returns the key value (if an unsigned int) from the profile. If no value set, returns the default value
int co_profile_set_float (co_obj_t *profile, const char *key, const size_t klen, const double value)
sets a specified profile value (if a float)
double co_profile_get_float (co_obj_t *profile, const char *key, const size_t klen)
returns the key value (if a float) from the profile. If no value set, returns the default value
int co_profile_export_file (co_obj_t *profile, const char *path)
exports a profile in memory to a file
co_obj_t * co_profiles_process (co_iter_t iter, void *context)
processes all loaded profiles with specified iterator function
Variables
co_obj_t _header
uint8_t _exttype
uint8_t _len
co_cb_t cb
co_obj_t * name
co_obj_t * data
Detailed Description
a key-value store for loading configuration information
Author
Josh King (jheretic), jking@chambana.net
Macro Definition Documentation
#define SCHEMA_ADD(K, V)
Value:
({ \
  co_obj_t *val = co_str8_create(V, sizeof(V), 0); \
  if (!co_tree_insert(self, K, sizeof(K), val)) \
    co_obj_free(val); \
  })
Function Documentation
int co_profile_add (const char * name, const size_t nlen)
adds a new profile
Parameters
name profile name
nlen length of profile name
References co_list_append().
{
  co_obj_t *new_profile = _co_profile_create(name, nlen);
  CHECK(_co_schemas_load(new_profile, _schemas), "Failed to initialize profile with schema.");
  CHECK(co_list_append(_profiles, new_profile), "Failed to add profile to list.");
  return 1;
error:
  co_obj_free(new_profile);
  return 0;
}
void co_profile_dump (co_obj_t * profile)
dumps profile data
Parameters
profile profile struct
int co_profile_export_file (co_obj_t * profile, const char * path)
exports a profile in memory to a file
Parameters
profile profile struct
path export path
References co_tree_root().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  int count = 0;
  FILE *config_file = fopen(path, "wb");
  CHECK(config_file != NULL, "Config file %s could not be opened", path);
  fprintf(config_file, "{\n");
  _co_profile_export_file_r(((co_profile_t*)profile)->data,
      co_tree_root(((co_profile_t*)profile)->data), &count, config_file);
  fprintf(config_file, "}");
  fclose (config_file);
  return 1;
error:
  return 0;
}
co_obj_t* co_profile_find (co_obj_t * name)
searches the profile list for a specified profile
Parameters
name profile name (search key)
References co_list_parse().
Referenced by co_profile_remove().
{
  CHECK(IS_STR(name), "Not a valid search index.");
  co_obj_t *result = NULL;
  CHECK((result = co_list_parse(_profiles, _co_profile_find_i, name)) != NULL, "Failed to find
       profile.");
  return result;
error:
  return NULL;
}
co_obj_t* co_profile_get (co_obj_t * profile, const co_obj_t * key)
returns the key value (if an int) from the profile. If no value set, returns the default value
Parameters
profile profile struct
key key in profile
klen key length
References co_tree_find().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK_MEM(((co_profile_t*)profile)->data);
  CHECK_MEM(key);
  char *kstr = NULL;
  size_t klen = co_obj_data(&kstr, key);
  co_obj_t *obj = NULL;
  CHECK((obj = co_tree_find(((co_profile_t*)profile)->data, kstr, klen)) != NULL, "
      Failed to find key %s.", kstr);
  return obj;
error:
  return NULL;
}
double co_profile_get_float (co_obj_t * profile, const char * key, const size_t klen)
returns the key value (if a float) from the profile. If no value set, returns the default value
Parameters
profile profile struct
key key in profile
klen key length
References co_tree_find().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK_MEM(((co_profile_t*)profile)->data);
  CHECK_MEM(key);
  co_obj_t *obj = NULL;
  CHECK((obj = co_tree_find(((co_profile_t*)profile)->data, key, klen)) != NULL, "
      Failed to find key %s.", key);
  CHECK(IS_FLOAT(obj), "Object is not a floating point value.");
  double *output;
  CHECK(co_obj_data((char **)&output, obj) >= 0, "Failed to read data from %s.", key);
  return *output;
error:
  return -1;
}
signed long co_profile_get_int (co_obj_t * profile, const char * key, const size_t klen)
returns the key value (if an int) from the profile. If no value set, returns the default value
Parameters
profile profile struct
key key in profile
klen key length
References co_tree_find().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK_MEM(((co_profile_t*)profile)->data);
  CHECK_MEM(key);
  co_obj_t *obj = NULL;
  CHECK((obj = co_tree_find(((co_profile_t*)profile)->data, key, klen)) != NULL, "
      Failed to find key %s.", key);
  CHECK(IS_INT(obj), "Object is not a signed integer.");
  signed long *output;
  CHECK(co_obj_data((char **)&output, obj) >= 0, "Failed to read data from %s.", key);
  return *output;
error:
  return -1;
}
size_t co_profile_get_str (co_obj_t * profile, char ** output, const char * key, const size_t klen)
returns the key value (if a string) from the profile. If no value set, returns the default value
Parameters
profile profile struct
output output buffer
key key in profile
klen key length
References co_tree_find().
Referenced by main().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK_MEM(((co_profile_t*)profile)->data);
  CHECK_MEM(key);
  co_obj_t *obj = NULL;
  CHECK((obj = co_tree_find(((co_profile_t*)profile)->data, key, klen)) != NULL, "
      Failed to find key %s.", key);
  CHECK(IS_STR(obj), "Object is not a string.");
  return co_obj_data((char **)output, obj);
error:
  return -1;
}
unsigned long co_profile_get_uint (co_obj_t * profile, const char * key, const size_t klen)
returns the key value (if an unsigned int) from the profile. If no value set, returns the default value
Parameters
profile profile struct
key key in profile
klen key length
References co_tree_find().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK_MEM(((co_profile_t*)profile)->data);
  CHECK_MEM(key);
  co_obj_t *obj = NULL;
  CHECK((obj = co_tree_find(((co_profile_t*)profile)->data, key, klen)) != NULL, "
      Failed to find key %s.", key);
  CHECK(IS_UINT(obj), "Object is not an unsigned integer.");
  unsigned long *output;
  CHECK(co_obj_data((char **)&output, obj) >= 0, "Failed to read data from %s.", key);
  return *output;
error:
  return -1;
}
int co_profile_import_files (const char * path)
imports available profiles from profiles directory
Parameters
path file path to the profiles directory
References process_files().
Referenced by main().
                                              {
  DEBUG("Importing files from %s", path);
  CHECK(process_files(path, _co_profile_import_files_i), "Failed to load all profiles.");
  return 1;
error:
  return 0;
}
int co_profile_import_global (const char * path)
imports global profile
Parameters
path file path to the global profile
References co_profile_set_str().
Referenced by main().
                                               {
  int ret = 0;
  FILE *config_file = NULL;
  jsmntok_t *tokens = NULL;
  if(_profile_global == NULL)
  {
    _profile_global = _co_profile_create("global", sizeof("global"));
  }
  _co_schemas_load(_profile_global, _schemas_global);
  DEBUG("Importing file at path %s", path);
  config_file = fopen(path, "rb");
  CHECK(config_file != NULL, "File %s could not be opened", path);
  fseek(config_file, 0, SEEK_END);
  long fsize = ftell(config_file);
  rewind(config_file);
  char *buffer = h_calloc(1, fsize + 1);
  CHECK(fread(buffer, fsize, 1, config_file) != 0, "Failed to read from file.");
  fclose(config_file);
  config_file = NULL;
  
  buffer[fsize] = '\0';
  tokens = _co_json_string_tokenize(buffer);
  typedef enum { START, KEY, VALUE, STOP } parse_state;
  parse_state state = START;
  size_t object_tokens = 0;
  char *key = NULL;
  size_t klen = 0;
  for (size_t i = 0, j = 1; j > 0; i++, j--)
  {
    jsmntok_t *t = &tokens[i];
    // Should never reach uninitialized tokens
    CHECK(t->start != -1 && t->end != -1, "Tokens uninitialized.");
    if (t->type == JSMN_ARRAY || t->type == JSMN_OBJECT)
      j += t->size;
    switch (state)
    {
      case START:
        CHECK(t->type == JSMN_OBJECT, "Invalid root element.");
        state = KEY;
        object_tokens = t->size;
        if (object_tokens == 0)
          state = STOP;
        CHECK(object_tokens % 2 == 0, "Object must have even number of children.");
        break;
      case KEY:
        object_tokens--;
        CHECK(t->type == JSMN_STRING, "Keys must be strings.");
        state = VALUE;
        key = _co_json_token_stringify(buffer, t);
        klen = t->end - t->start;
        break;
      case VALUE:
        CHECK(t->type == JSMN_STRING, "Values must be strings.");
        if(key != NULL && klen > 0)
        {
          if(!co_profile_set_str(_profile_global, key, klen + 1, _co_json_token_stringify
      (buffer, t), t->end - t->start + 1))
          {
            INFO("Value not in schema.");
          }
          
        }
        key = NULL;
        klen = 0;
        object_tokens--;
        state = KEY;
        if (object_tokens == 0)
          state = STOP;
        break;
      case STOP:
        // Just consume the tokens
        break;
      default:
        SENTINEL("Invalid state %u", state);
    }
  }
  ret = 1;
error:
  if(config_file != NULL) fclose(config_file);
  if (buffer) h_free(buffer);
  if (tokens) h_free(tokens);
  return ret;
}
int co_profile_remove (const char * name, const size_t nlen)
removes profile with given name
Parameters
name profile name
nlen length of profile name
References co_list_delete(), and co_profile_find().
{
  co_obj_t *n = co_str8_create(name, nlen, 0);
  co_obj_t *prof = co_profile_find(n);
  prof = co_list_delete(_profiles, prof);
  CHECK(prof != NULL, "Failed to remove profile.");
  co_obj_free(n);
  return 1;
error:
  co_obj_free(n);
  return 0;
}
int co_profile_set_float (co_obj_t * profile, const char * key, const size_t klen, const double value)
sets a specified profile value (if a float)
Parameters
profile profile struct
key key in profile
klen key length
value key's value
References co_tree_set_float().
{
    CHECK(IS_PROFILE(profile),"Not a profile.");
    CHECK(co_tree_set_float(((co_profile_t*)profile)->data, key, klen, value),
       
            "No corresponding key %s in schema, can't set %s:%lf",
            key, key, value);
    return 1;
error:
    return 0;
}
int co_profile_set_int (co_obj_t * profile, const char * key, const size_t klen, const signed long value)
sets a specified profile value (if an int)
Parameters
profile profile struct
key key in profile
klen key length
value key's value
References co_tree_set_int().
{
  CHECK(IS_PROFILE(profile),"Not a profile.");
  CHECK(co_tree_set_int(((co_profile_t*)profile)->data, key, klen, value),
            "No corresponding key %s in schema, can't set %s:%ld",
            key, key, value);
    return 1;
error:
    return 0;
}
int co_profile_set_str (co_obj_t * profile, const char * key, const size_t klen, const char * value, const size_t vlen)
sets a specified profile value (if a string)
Parameters
profile profile struct
key key in profile
klen key length
value key's value
vlen value length
References co_tree_set_str().
Referenced by co_profile_import_global().
{
    CHECK(IS_PROFILE(profile),"Not a profile.");
    CHECK(co_tree_set_str(((co_profile_t*)profile)->data, key, klen, value, vlen
      ),
            "No corresponding key %s in schema, can't set %s:%s",
            key, key, value);
    return 1;
error:
    return 0;
}
int co_profile_set_uint (co_obj_t * profile, const char * key, const size_t klen, const unsigned long value)
sets a specified profile value (if an unsigned int)
Parameters
profile profile struct
key key in profile
klen key length
value key's value
References co_tree_set_uint().
{
    CHECK(IS_PROFILE(profile),"Not a profile.");
    CHECK(co_tree_set_uint(((co_profile_t*)profile)->data, key, klen, value),
            "No corresponding key %s in schema, can't set %s:%lu",
            key, key, value);
    return 1;
error:
    return 0;
}
int co_profiles_create (const size_t index_size)
create global profiles list
Parameters
index_size size of index for profiles list (16 or 32 bits)
co_obj_t* co_profiles_process (co_iter_t iter, void * context)
processes all loaded profiles with specified iterator function
Parameters
iter iterator function callback
context additional parameters for iterator
References co_list_parse().
{
  return co_list_parse(_profiles, iter, context);
}
int co_schema_register (co_cb_t cb)
register a callback for populating a profile schema
Parameters
cb schema callback
References co_list_append().
{
  DEBUG("Registering schema.");
  CHECK(co_list_append(_schemas, _co_schema_create(cb)), "Failed to register schema.");
  return 1;
error:
  return 0;
}
int co_schema_register_global (co_cb_t cb)
register a callback for populating global profile
Parameters
cb schema callback
References co_list_append().
{
  DEBUG("Registering global schema.");
  CHECK(co_list_append(_schemas_global, _co_schema_create(cb)), "Failed to register schema.")
      ;
  return 1;
error:
  return 0;
}
int co_schemas_load (co_obj_t * profile)
load schemas for specified profile
Parameters
profile profile to load schemas for
Variable Documentation
co_obj_t* name
command name