name: "Commotion Wireless"
description: "Commotion is an open-source communication tool that uses mobile phones, computers, and other wireless devices to create decentralized mesh networks."

encoding: utf-8

url: "test.commotionwireless.net"
port: 80


permalink: pretty 
